// last updated 07.04.2011
var pClientIsGecko=(window.controllers)?true:false;
var pClientIsOpera=(window.opera)?true:false;
var pClientIsIE=(document.all&&!pClientIsOpera)?true:false;
var pClientIsIE5=(pClientIsIE&&/MSIE 5\.0/.test(navigator.appVersion))?true:false;
var pClientIsIE55=(pClientIsIE&&/MSIE 5\.5/.test(navigator.appVersion))?true:false;
var pClientIsIE6=(pClientIsIE&&/MSIE 6\.0/.test(navigator.appVersion))?true:false;
var pClientIsIE7=(pClientIsIE&&/MSIE 7\.0/.test(navigator.appVersion))?true:false;
var pClientIsIElte55=(pClientIsIE&&(pClientIsIE5||pClientIsIE55)&&!pClientIsIE7);
var pClientIsIElte6=(pClientIsIE&&(pClientIsIElte55||pClientIsIE6)&&!pClientIsIE7);
var pClientIsMac=(/Mac/.test(navigator.appVersion))?true:false;
var DOM={isParentOf:function(A,B){while(B&&(B!=A)){B=B.parentNode}return(B==A)},getParentOrSelf:function(B,A){A=A.toLowerCase();while(B.nodeName.toLowerCase()!=A&&B.parentNode){B=B.parentNode}return B},addClass:function(B,A){B.className+=" "+A},removeClass:function(C,B){var A=new RegExp("\\b"+B+"\\b","g");if(A.test(C.className)){C.className=C.className.replace(A," ")}}};function getDimensions(F){var C={x:0,y:0,w:0,h:0};if(document.getBoxObjectFor){var A=document.getBoxObjectFor(F);C.x=A.x;C.y=A.y;C.w=A.width;C.h=A.height}else{if(F.getBoundinpClientRect){var B=/MSIE 5\.0/g;var A=F.getBoundinpClientRect();C.x=A.left;C.y=A.top;C.w=(A.right-A.left);C.h=(A.bottom-A.top);if(document.compatMode&&document.compatMode!="BackCompat"){var D=(document.body.scrollTop==0)?(window.pageYOffset)?window.pageYOffset:(document.body.parentElement)?document.body.parentElement.scrollTop:0:document.body.scrollTop;C.x+=document.documentElement.scrollLeft-2;C.y+=D-2}else{if(!pClientIsIE5){C.x+=document.body.scrollLeft-2;C.y+=document.body.scrollTop-2}}}else{C.w=F.offsetWidth;C.h=F.offsetHeight;while(F){C.x+=F.offsetLeft;C.y+=F.offsetTop;if(F.offsetParent){F=F.offsetParent}else{break}}}}var E;if(E=document.getElementById("bodyconstraint")){C.x-=E.offsetLeft}return C}String.prototype.deCode=function(){return this.replace(/[a-zA-Z]/g,function(A){return String.fromCharCode((A<="Z"?90:122)>=(A=A.charCodeAt(0)+13)?A:A-26)})};Date.prototype.getTwoDigitMonth=function(){var A=(this.getMonth()+1).toFixed().toString();if(A.length==1){A="0"+A}return A};Date.MILLISECONDS_PER_DAY=Date.prototype.MILLISECONDS_PER_DAY=86400000;Date.prototype.getMondayToSundayDay=function(){var A=this.getDay();A--;if(A==-1){A=6}return A};if(!Array.prototype.walk){Array.prototype.walk=function(C){var A=[],B=this.length;while(B--){A.push(C(this[B]))}return A.reverse()}}if(!Array.prototype.flatten){Array.prototype.flatten=function(){var B=[],C=-1,A=this.length;while(++C<A){B=B.concat(this[C].constructor==Array?this[C].flatten():this[C])}return B}}if(!Array.indexOf){Array.prototype.indexOf=function(B){for(var A=0;A<this.length;A++){if(this[A]==B){return A}}return -1}}
var td;

function buildCal(K,E,J){var B=[31,0,31,30,31,30,31,31,30,31,30,31];td=new Date();td.setDate(tr.currentDay);if(!K){K=td.getFullYear()}if(!E){E=td.getMonth()+1}if(!J){J=td.getDate}var D=calendar.caldt;var C=new Date(K,E-1,1);var G=C.getDay();B[1]=(((C.getFullYear()%100!=0)&&(C.getFullYear()%4==0))||(C.getFullYear()%400==0))?29:28;var O='<table class="caltable" border="0" cellspacing="0"><tr>';O+='<td class="calheader monthYear" colspan="4">';O+='<select name="ym" class="ym_month" onchange="goYearMonth( this.options[this.selectedIndex].value );">';var F=td.getMonth()+1;var N=td.getFullYear();var I=0;for(n=0;n<=11;n++){O+='<option value="'+N+"-"+F+'"';if(F==E&&N==K){O+=' selected="selected"';I=1}else{I=0}O+=">"+months[F-1]+" "+N+"</option>";F++;if(F>12){F=1;N++}}O+=" </select>";O+='</td><td class="calheader monthYear" colspan="2">';if(K==td.getFullYear()&&E==td.getMonth()+1){O+='<a class="calPrevMonth" href="javascript:void(0)"><img src="'+tr.icons+tr.iconPrevMonth2+'" width="16" height="24" alt="'+tr.prevMonth+'" /></a>'}else{O+='<a class="calPrevMonth" href="" onclick="prevMonth( '+K+","+E+' ); return false;" title="'+tr.prevMonth+'"><img src="'+tr.icons+tr.iconPrevMonth+'" width="16" height="24" alt="'+tr.prevMonth+'" /></a>'}if(I==1){O+='<a class="calNextMonth" href="javascript:void(0);"><img src="'+tr.icons+tr.iconNextMonth2+'" width="16" height="24" alt="'+tr.nextMonth+'" /></a>'}else{O+='<a class="calNextMonth" href="" onclick="nextMonth( '+K+","+E+' ); return false;" title="'+tr.nextMonth+'"><img src="'+tr.icons+tr.iconNextMonth+'" width="16" height="24" alt="'+tr.nextMonth+'" /></a>'}O+='</td><td class="calheader monthYear">';O+='<a class="calCloseLink" href="#" onclick="closeCal(); return false;"><img src="'+tr.icons+'delete.gif" width="16" height="24" alt="" title="'+tr.closeCalendar+'" /></a>';O+="</td></tr>";O+='<tr class="dayNames">';var M;for(dn=0;dn<7;dn++){M="";if((dn%7==5)||(dn%7==6)){M+=" weekend"}O+='<td class="'+M+'">'+days[dn]+"</td>"}O+='</tr><tr class="days">';for(i=1;i<=42;i++){var L=i-(G+6)%7;if(L>B[E-1]||L<1){L="&nbsp;"}M="";var A=0;if((i%7==0)||(i%7==6)){M+=" weekend"}if(L>0){var H=new Date(K,E-1,L);if((H.getFullYear()==K)&&(H.getMonth()+1==E)&&(H.getDate()==J)){M+=" selected";A=1}if((H.getFullYear()==td.getFullYear())&&(H.getMonth()==td.getMonth())&&(H.getDate()==td.getDate())){M+=" today";A=1}else{if(H>td){M+=" future";A=1}else{if(H<td){M+=" past"}}}}O+='<td class="'+M+'">';if(A){O+='<a href="#" onclick="pickDate( '+K+","+E+","+L+",'"+D+"' ); return false;\">"+L+"</a>"}else{O+=L}O+="</td>";if(((i)%7==0)&&(i<36)){O+='</tr><tr class="days">'}}O+='</tr></table>';document.getElementById("calendar").innerHTML=O}
function showCalendar(G,J,A){getDimensions(G);if(document.getElementById){var F=document.getElementById(J);var C=getChildImage(G);var E=DOM.getParentOrSelf(G,"form");calendar.cal=F;calendar.caldt=A;calendar.calf=E;var I=E[A+"_year_month"].value.split("-");y=I[0];m=I[1];d=E[A+"_monthday"].value;if(y==="0"){y=new Date().getFullYear()};buildCal(y,m,d);var D=getDimensions(C);var B=D.x,H=(D.y+C.offsetHeight);F.style.left=(B+23)+"px";F.style.top=H+"px";F.style.display="block";}}
function closeCal(){calendar.cal.style.display="none"}
function prevMonth(B,A){if(new Date(B,A-1,1)<td){return }if(A>1){A--}else{A=12;B--}buildCal(B,A)}
function nextMonth(B,A){if(A<12){A++}else{A=1;B++}buildCal(B,A)}
function goYearMonth(A){var B=A.split("-");buildCal(B[0],B[1])}
function pickDate(E,A,D,B){var C=calendar.calf;var B=calendar.caldt;C[B+"_year_month"].value=E+"-"+A;C[B+"_monthday"].value=D;if(B=="checkin"){checkDateOrder(C,"checkin_monthday","checkin_year_month","checkout_monthday","checkout_year_month")}closeCal();}
function initDaySelect(){var A=document.getElementsByTagName("form");for(var B=0;B<A.length;B++){if(A[B].checkin_monthday){updateDaySelect(A[B])}}}
function updateDaySelect(J){if(pClientIsIE5&&pClientIsMac){return }var M=DOM.getParentOrSelf(J,"form");if(M.getAttribute("id")!=="frm"&&M.className!=="availForm"){return }if(!M.checkin_monthday||!M.checkout_monthday||!M.checkin_year_month||!M.checkout_year_month){return }if(M.checkin_monthday.value==="0"&&M.checkout_monthday.value==="0"&&M.checkin_year_month.value==="0"&&M.checkout_year_month.value==="0"){return }var H=M.checkin_monthday,O=M.checkout_monthday,G,N,Q;if(M.checkin_year_month.value!=="0"){G=M.checkin_year_month.value.split("-")}if(M.checkout_year_month.value!=="0"){N=M.checkout_year_month.value.split("-")}var I=Math.max(H.selectedIndex,0),B=Math.max(O.selectedIndex,0),E=H[I].value,L=O[B].value,K=[],A,F;H.innerHTML="";O.innerHTML="";if(!pClientIsIE5){var P=function(){};}
function D(Y,U,R,X,W){var V,T,S;for(V=0;V<Y;V++){S=document.createElement("option");T=V+1;if(U.value!=="0"){T=R[V]+" "+T}S.innerHTML=T;S.value=(V+1);if(V>0&&W==V+1){S.defaultSelected=S.selected=true}X.appendChild(S)}}K=buildDaysForMonth(G[0],G[1]);var C=31;if(M.checkin_year_month.value!=="0"){C=K.length}D(C,M.checkin_year_month,K,H,E);K=buildDaysForMonth(N[0],N[1]);C=31;if(M.checkout_year_month.value!=="0"){C=K.length}D(C,M.checkout_year_month,K,O,L);if(pClientIsIElte6){H.value=E;O.value=L}}
function buildDaysForMonth(D,G){var B=new Date(D,G-1);var E=B.getMonth();var A=[],C;while(B.getMonth()==E){C=(B.getDay()==0)?6:(B.getDay()-1);A.push(days[C]);var F=B.getDate();B.setDate(B.getDate()+1);if(B.getDate()==F){B.setDate(B.getDate()+1)}}return A}
function checkDateOrder(G,C,B,H,E){var one_day=1000*60*60*24;var J=DOM.getParentOrSelf(G,"form"),K,L=new Date(0),I=new Date(0),A,F=new Date();if(J[C].value!=="0"){L.setDate(J[C].value);}if(J[B].value!=="0"){K=J[B].value.split("-");L.setFullYear(K[0]);L.setMonth(K[1]-1);}L.setHours(12);L.setMinutes(0);L.setSeconds(0);if(J[H] != undefined && J[H].value!=="0"){I.setDate(J[H].value);}if(J[E] != undefined && J[E].value!=="0"){K=J[E].value.split("-");I.setFullYear(K[0]);I.setMonth(K[1]-1);}I.setHours(12);I.setMinutes(0);I.setSeconds(0);if(J[B].value!=="0"){while(L.getMonth()!=J[B].value.split("-")[1]-1){L.setDate(L.getDate()-1);J[C].value=L.getDate();}var D=L.getMonth()+1;J[B].value=L.getFullYear()+"-"+D;}var days_diff = ((L-I)/one_day);if(days_diff >= (1-minimum_nights)){I.setTime(L.getTime()+minimum_nights*Date.prototype.MILLISECONDS_PER_DAY);A=I.getMonth()+1;if(J[C].value!=="0"){if(J[H] != undefined) J[H].value=I.getDate();}if(J[B].value!=="0"){if(J[E] != undefined) J[E].value=I.getFullYear()+"-"+A;}}}
function getChildImage(A){A=A.firstChild;while(A.nodeName.toLowerCase()!="img"&&A.nextSibling){A=A.nextSibling}return A}
function getParentOrSelf(B,A){A=A.toLowerCase();while(B.nodeName.toLowerCase()!=A&&B.parentNode){B=B.parentNode}return B}