function catchEvent(b,a,c){if(typeof(b)=="string"){b=document.getElementById(b);}if(b==null){return;}if(b.addEventListener){b.addEventListener(a,c,false);
}else{if(b.attachEvent){b.attachEvent("on"+a,c);}}}function uncatchEvent(b,a,c){if(typeof(b)=="string"){b=document.getElementById(b);}if(b==null){return;
}if(b.removeEventListener){b.removeEventListener(a,c,false);}else{if(b.detachEvent){b.detachEvent("on"+a,c);}}}function cancelEvent(a){a=a?a:window.event;
if(a.stopPropagation){a.stopPropagation();}if(a.preventDefault){a.preventDefault();}a.cancelBubble=true;a.cancel=true;a.returnValue=false;return false;
}function Position(a,b){this.X=a;this.Y=b;this.Add=function(d){var c=new Position(this.X,this.Y);if(d!=null){if(!isNaN(d.X)){c.X+=d.X;}if(!isNaN(d.Y)){c.Y+=d.Y;
}}return c;};this.Subtract=function(d){var c=new Position(this.X,this.Y);if(d!=null){if(!isNaN(d.X)){c.X-=d.X;}if(!isNaN(d.Y)){c.Y-=d.Y;}}return c;};this.Min=function(d){var c=new Position(this.X,this.Y);
if(d==null){return c;}if(!isNaN(d.X)&&this.X>d.X){c.X=d.X;}if(!isNaN(d.Y)&&this.Y>d.Y){c.Y=d.Y;}return c;};this.Max=function(d){var c=new Position(this.X,this.Y);
if(d==null){return c;}if(!isNaN(d.X)&&this.X<d.X){c.X=d.X;}if(!isNaN(d.Y)&&this.Y<d.Y){c.Y=d.Y;}return c;};this.Bound=function(c,e){var d=this.Max(c);return d.Min(e);
};this.Check=function(){var c=new Position(this.X,this.Y);if(isNaN(c.X)){c.X=0;}if(isNaN(c.Y)){c.Y=0;}return c;};this.Apply=function(c){if(typeof(c)=="string"){c=document.getElementById(c);
}if(c==null){return;}if(!isNaN(this.X)){c.style.left=this.X+"px";}if(!isNaN(this.Y)){c.style.top=this.Y+"px";}};}function absoluteCursorPostion(a){a=a?a:window.event;
if(isNaN(window.scrollX)){return new Position(a.clientX+document.documentElement.scrollLeft+document.body.scrollLeft,a.clientY+document.documentElement.scrollTop+document.body.scrollTop);
}else{return new Position(a.clientX+window.scrollX,a.clientY+window.scrollY);}}function dragObject(a,d,e,h,l,j,g,c){if(typeof(a)=="string"){a=document.getElementById(a);
}if(a==null){return;}if(e!=null&&h!=null){var p=e.Min(h);h=e.Max(h);e=p;}var o=null;var i=null;var k=false;var m=false;var f=false;function q(s){if(k||!m||f){return;
}k=true;if(l!=null){l(s,a);}o=absoluteCursorPostion(s);i=new Position(parseInt(a.style.left),parseInt(a.style.top));i=i.Check();catchEvent(document,"mousemove",n);
catchEvent(document,"mouseup",b);return cancelEvent(s);}function n(t){if(!k||f){return;}var s=absoluteCursorPostion(t);s=s.Add(i).Subtract(o);s=s.Bound(e,h);
s.Apply(a);if(j!=null){j(s,a);}return cancelEvent(t);}function b(s){r();return cancelEvent(s);}function r(){if(!k||f){return;}uncatchEvent(document,"mousemove",n);
uncatchEvent(document,"mouseup",b);o=null;i=null;if(g!=null){g(a);}k=false;}this.Dispose=function(){if(f){return;}this.StopListening(true);a=null;d=null;
e=null;h=null;l=null;j=null;g=null;f=true;};this.StartListening=function(){if(m||f){return;}m=true;catchEvent(d,"mousedown",q);};this.StopListening=function(s){if(!m||f){return;
}uncatchEvent(d,"mousedown",q);m=false;if(s&&k){r();}};this.IsDragging=function(){return k;};this.IsListening=function(){return m;};this.IsDisposed=function(){return f;
};if(typeof(d)=="string"){d=document.getElementById(d);}if(d==null){d=a;}if(!c){this.StartListening();}}